### ISSUE TITLE
mqttClientFactory uses deprecated method 

### ISSUE THREAD

**Issue by drunkhacker** [spring-cloud-stream-app-starters/mqtt#17]
`DefaultMqttPahoClientFactory` deprecated the following methods in version 4.3.23
```
setServerURIs
setUserName
setPassword
setCleanSession
setConnectionTimeout
setKeepAliveInterval
```

see: https://docs.spring.io/autorepo/docs/spring-integration/4.3.23.RELEASE/api/org/springframework/integration/mqtt/core/DefaultMqttPahoClientFactory.html#setServerURIs-java.lang.String...-

As this library doesn't fix the version of spring-integration-mqtt, when I try to use this it captures 5.3.2 which is the current version. And it failed to construct bean as those methods are removed from version >= 5

Please use `MqttConnectOptions` or you need to fix the version of dependencies. 

Thank you.

**Comment by garyrussell** [comment]
This is replaced by the new function-based versions in https://github.com/spring-cloud/stream-applications which do use the newer configuration:

https://github.com/spring-cloud/stream-applications/blob/66c501571929d048626be06a232c427adff43b7a/functions/common/mqtt-common/src/main/java/org/springframework/cloud/fn/common/mqtt/MqttConfiguration.java#L45-L51

**Comment by drunkhacker** [comment]
ah, thanks for letting me know the newer one :+1:
